name: Test solution code simply

on:
    push:
        paths:
            - "solutions"

jobs:
    check-file:
        name: Check for solution files
        runs-on: ubuntu-latest
        outputs:
            status: ${{ steps.check-diff.outputs.status }}
        steps:
            - uses: actions/checkout@v3
            - name: Check committed files
              id: check-diff
              run: bash .github/scripts/diff-check.sh ${{ github.sha }} "$GITHUB_OUTPUT"

    test:
        name: Test solution files
        runs-on: ubuntu-latest
        needs: ["check-file"]
        if: ${{ needs.check-file.outputs.status == 'TRUE' }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
                  check-latest: true
            - uses: egor-tensin/setup-gcc@v1
              with:
                  version: latest
                  platform: x64
            - name: Test solution files
              run: bash .github/scripts/run-test.sh ${{ github.sha }}
            - name: Commit README files
              run: bash .github/scripts/commit.sh "$GITHUB_OUTPUT"
              env:
                  REPOSITORY: ${{ github.repository }}
                  MESSAGE: "Add README files with scoring results"
